server:
  # setup port
  port: 9010
  # get domain from serverapp
  base:
    url: http://localhost:9000

spring:
  # setup project name
  application:
    name: Client App
  # open all http method => default get & post
  mvc:
    hiddenmethod:
      filter:
        enabled: true
